### ISSUE TITLE
Missing fastmovingaverage.c file to work on Windows

### ISSUE THREAD

**Issue by LochanaMendis** [jirispilka/CTG-database-2017#1]
Can you please upload the fastmovingaverage.c file as the provided compiled file fastmovingaverage.mexa64 is not working on Windows OS. Or if you could provide the fastmovingaverage.mexw64 file it is great!

**Comment by jirispilka** [comment]
Hi, thanks for pointing that out. I have missed to include it. 
I have just added the file and pushed. Hope it helps. 

Unfortunately, I'm not able to verify as I'm no longer using Matlab. 

I'm not sure what is your use case, if you would be interested, I have a lot of code and parts of my work just sitting at my hard drive without much use :).

**Comment by LochanaMendis** [comment]
Hi Spilka,

Thank you very much for providing the file. 

I am very much interested in your automatic cardiotocography analysis work. 
I will email you regarding my work and your set of code will help me a lot.

**Comment by jirispilka** [comment]
Hi @LochanaMendis ,
I'm no longer affiliated with university I have only personal email id. 
Should I drop a line to your email id that I found in one of your papers? ***@ieee.org?

**Comment by LochanaMendis** [comment]
Hi @jirispilka ,

Yes, that is much appreciated.
The email I sent to the university email bounced back.
